apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
  - name: http
    port: {{PORT}}              # service port (e.g., 80)
    targetPort: {{TARGET_PORT}} # container port (e.g., 8080)
    protocol: TCP

---

# kubectl expose deployment <deployment-name> \
#   --name=<service-name> \
#   --port=<service-port> \
#   --target-port=<container-port> \
#   --type=ClusterIP \
#   -n <namespace>
