apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-headless
  namespace: {{NAMESPACE}}
spec:
  clusterIP: None
  selector:
    app: {{APP_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: {{TARGET_PORT}}

