apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-lb
  namespace: {{NAMESPACE}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: {{APP_NAME}}
spec:
  type: LoadBalancer
  selector:
    app: {{APP_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: {{TARGET_PORT}}
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-internal
  namespace: {{NAMESPACE}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: {{APP_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: {{TARGET_PORT}}

---

# kubectl expose deployment <deployment-name> \
#   --name=<service-name> \
#   --port=<service-port> \
#   --target-port=<container-port> \
#   --type=LoadBalancer \
#   -n <namespace>
