apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-nodeport
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  type: NodePort
  selector:
    app: {{APP_NAME}}
  ports:
  - name: http
    port: {{PORT}}              # internal cluster port
    targetPort: {{TARGET_PORT}} # container port
    protocol: TCP
    nodePort: {{NODE_PORT}}     # optional (e.g., 32000)

---
# kubectl expose deployment <deployment-name> \
#   --name=<service-name> \
#   --port=<service-port> \
#   --target-port=<container-port> \
#   --type=NodePort \
#   -n <namespace>
