---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{SERVICE_ACCOUNT}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
automountServiceAccountToken: false

---
# Headless service is REQUIRED for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-headless
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  clusterIP: None
  selector:
    app: {{APP_NAME}}
  ports:
  - port: {{PORT}}
    targetPort: {{PORT}}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  serviceName: {{APP_NAME}}-headless     # required
  replicas: {{REPLICAS}}                 # e.g., 3
  podManagementPolicy: Parallel          # faster rollouts

  updateStrategy:
    type: RollingUpdate                   # best practice for most apps

  selector:
    matchLabels:
      app: {{APP_NAME}}

  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      serviceAccountName: {{SERVICE_ACCOUNT}}
      automountServiceAccountToken: false

      containers:
      - name: {{APP_NAME}}
        image: {{IMAGE}}:{{TAG}}          # e.g., postgres:16
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: {{PORT}}

        # ------------- ENV VARS ----------------
        env:
        - name: ENVIRONMENT
          value: "production"

        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: {{CONFIGMAP}}
              key: {{CONFIG_KEY}}

        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: {{SECRET}}
              key: {{SECRET_KEY}}
        # ---------------------------------------

        resources:
          requests:
            cpu: "{{CPU_REQUEST}}"
            memory: "{{MEM_REQUEST}}"
          limits:
            cpu: "{{CPU_LIMIT}}"
            memory: "{{MEM_LIMIT}}"

        # ------------- VOLUME MOUNTS ------------
        volumeMounts:
        - name: data
          mountPath: {{MOUNT_PATH}}       # e.g., /var/lib/data
        # ----------------------------------------

  # ------------- PERSISTENT VOLUMES ------------
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{STORAGE_CLASS}}  # e.g., gp3
      resources:
        requests:
          storage: {{STORAGE_SIZE}}        # e.g., 10Gi
  # ----------------------------------------------
